### ISSUE TITLE
依赖包安装完毕后 , npm run dev 失败

### ISSUE THREAD

**Issue by maybeee19** [mcc108/resume#5]
我该如何解决 如下错误: 
TypeError: Cannot read property 'properties' of undefined
    at module.exports (D:\wxcodes\git\resume\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at Object.<anonymous> (D:\wxcodes\git\resume\node_modules\webpack-dev-server\bin\webpack-dev-server.js:60:25)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! resume@1.5.0 dev: `webpack-dev-server --mode=development --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the resume@1.5.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2019-06-20T09_08_49_906Z-debug.log

**Comment by cong-min** [comment]
webpack 版本问题，见 https://github.com/webpack/webpack/issues/8082
